//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoStore.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime Date { get; set; }
        public string ReviewerName { get; set; }
        public string ReviewerLocation { get; set; }
        public string ReviewerCity { get; set; }
        public string ReviewerCountry { get; set; }
        public string Rating { get; set; }
        public string Details { get; set; }
        public int UserId { get; set; }
        public int MediaId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Media Medium { get; set; }
    }
}
